run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - gofumpt
    - govet
    - errcheck
    - staticcheck
    - gocyclo
    - revive
    - err113

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
  exclude-use-default: false